create database e_commerce;
use e_commerce;

select * from Customers;
select * from Products;
select * from Orders;

-- Find the total revenue generated by each product.
SELECT Product_Name,
SUM(o.Quantity * p.Price) AS Total_Revenue
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
GROUP BY Product_Name;

-- List the top 5 products based on total revenue in 2025.
SELECT Product_Name,
SUM(o.Quantity * p.Price) AS Total_Revenue2025
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
WHERE year(o.Order_Date)= 2025
GROUP BY Product_Name
ORDER BY Total_Revenue2025 DESC
LIMIT 5;

-- Find total sales and number of orders per month for 2024 and 2025.
SELECT Month(o.Order_Date) AS Months,
COUNT(o.Order_ID) AS Num_orders,
SUM(o.Quantity * p.Price) AS Total_Sales2024_2025
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
WHERE YEAR(o.Order_Date) in (2024,2025)
GROUP BY Months;

-- Calculate the average order value (AOV) for each customer.
SELECT c.Customer_ID,
AVG(o.Quantity) AS Average_Order_Value
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
group by Customer_ID;

-- Find customers who haven’t made any purchase in the last 6 months.
SELECT c.Customer_ID, c.Customer_Name,
MAX(o.Order_Date) AS LastOrderDate
FROM Customers c
Left JOIN Orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY Customer_ID,Customer_Name
HAVING MAX(Order_Date) IS NULL OR MAX(Order_Date) < CURRENT_DATE() -INTERVAL 6 MONTH;


-- List the top 5 cities contributing the highest total sales.
SELECT c.City ,
SUM(o.Quantity * p.Price) AS Total_Sales
FROM Customers c 
JOIN Orders o
ON c.Customer_ID = o.Customer_ID 
JOIN Products p
ON p.Product_ID = o.Product_ID 
GROUP BY City;

-- Identify which category (Electronics or Accessories) has the highest average selling price.
SELECT Category,
ROUND(AVG(Price),2) AS Avg_selling_Price
FROM Products 
GROUP BY Category
ORDER BY Price DESC;

-- Find the product with the highest number of units sold overall.
SELECT p.Product_Name,
SUM(o.Quantity) AS UnitsSolds
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
group by Product_Name
ORDER BY UnitsSolds DESC
LIMIT 5;

-- Calculate the total number of unique customers who purchased in each quarter.
SELECT CONCAT(YEAR(Order_Date),' Q',QUARTER(Order_Date)) AS YearQuater,
count(distinct(Customer_ID)) AS UniqueCustomers
FROM Orders
GROUP BY Customer_ID
ORDER BY YearQuater;

-- Find products that were never ordered.
SELECT p.Product_ID,p.Product_Name
FROM Products p
LEFT JOIN Orders o
ON P.Product_ID = o.Product_ID
WHERE o.Order_ID IS NULL;

-- Calculate the Rolling 30-Day Average of Sales Revenue.
SELECT AVG(o.Quantity * p.Price) AS Avg_sales_Revenue
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
WHERE DAY(o.Order_Date);

-- Determine the average delivery time (DeliveryDate − OrderDate) per product.
SELECT Product_Name,
ROUND((DATEDIFF(Delivery_Date,Order_Date)) ,2) AS Avg_delivery_Time
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
GROUP BY Product_Name;

-- Identify the month with the highest total revenue.
SELECT MONTH(o.Order_Date) AS Months,
SUM(o.Quantity * p.Price) AS Total_Revenue
FROM Products p
JOIN Orders o
ON p.Product_ID = o.Product_ID
GROUP BY Order_Date
ORDER BY Total_Revenue DESC
LIMIT 5;

-- Find repeat customers (those who placed more than 3 orders).
SELECT c.Customer_ID, c.Customer_Name,
COUNT(o.Order_ID) AS Order_Count 
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY Customer_ID,c.Customer_Name
HAVING COUNT(o.Order_ID) >=3
Order BY Order_Count DESC;


-- Find customers whose first order was in 2025.
SELECT c.Customer_ID,c.Customer_Name,
MIN(o.Order_Date) AS First_order
FROM Customers c
JOIN Orders o 
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
HAVING YEAR(MIN(o.Order_Date)=2025);

-- Find the top 5 products with the highest revenue per unit sold (Revenue ÷ Quantity).
SELECT p.Product_Name, 
SUM(o.Quantity) AS UnitsSold,
SUM(o.Quantity * p.Price) AS TotalRevenue,
SUM(o.Quantity * p.Price) / SUM(o.Quantity) AS revenue_per_unit_sold
FROM Products p
JOIN Orders o
ON p.Product_ID =o.Product_ID
GROUP BY Product_Name
ORDER BY revenue_per_unit_sold DESC
LIMIT 5;


-- Identify customers who bought products from multiple categories.
SELECT c.Customer_ID, c.Customer_Name,
COUNT(DISTINCT(p.Category)) AS categoriesbought
FROM Orders o
JOIN Customers c
ON c.Customer_ID =o.Customer_ID
JOIN Products p
ON p.Product_ID = o.Product_ID
GROUP BY Customer_ID, Customer_Name
HAVING COUNT(DISTINCT(p.Category)) > 1
ORDER BY categoriesbought DESC;

-- Find the product with the most variation (standard deviation) in sales quantity.
SELECT p.Product_ID, p.Product_Name,
ROUND(STDDEV_SAMP(o.Quantity),2) AS std_Devi_Quantity
FROM Products p
LEFT JOIN Orders o 
ON p.Product_ID = o.Product_ID
GROUP BY Product_ID, Product_Name;

-- Identify potential churn: customers whose last purchase was more than 180 days ago.
SELECT c.Customer_ID, c.Customer_Name,
MAX(o.Order_Date) AS LastOrder
FROM Customers c 
JOIN Orders o 
ON c.Customer_ID =o.Customer_ID
GROUP BY Customer_ID,Customer_Name
HAVING MAX(o.Order_Date)  < CURRENT_Date() - INTERVAL 180 DAY;




